# Generated by Django 4.2.4 on 2023-09-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrineStripAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colors", models.JSONField(default=dict)),
                ("image", models.ImageField(upload_to="urine_strips/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
